const width = 5;
const height = 17;
const area = width * height;
console.log('the area is', area);
console.log('the variable area is', typeof area);
const bill = 25;
const payment = 32;
const change = payment - bill;
console.log('your change is', change);
console.log('the variable change is', typeof change);
const quizzes = 45;
const midterm = 79;
const final = 85;
const grade = (quizzes + midterm + final) / 3;
console.log('final grade is', grade);
console.log('the variable grade is', typeof grade);
const firstName = 'Alex';
const lastName = 'Ehrenkranz';
const fullName = firstName + ' ' + lastName;
console.log('full name is', fullName);
console.log('variable fullName is', typeof fullName);
const ph = 7;
const isAcidic = ph < 7;
console.log('this is acidic', isAcidic);
console.log('typeof isAcidic', typeof isAcidic);
const headCount = 111;
const isSparta = headCount === 300;
console.log('is this sparta?', isSparta);
console.log('typeof isSparta', typeof isSparta);
let motto = fullName;
motto = motto + ' is the GOAT';
console.log(motto);
console.log('typeof motto', typeof motto);
